# Generated by Django 5.1.2 on 2024-10-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityweather',
            name='city_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
